version: '3.1'
services:

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: ${AUTOHEAL_CONTAINER_LABEL}
      AUTOHEAL_INTERVAL: ${AUTOHEAL_INTERVAL}
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  caiman_api:
    restart: always
    build: ./api
    image: caiman_api:latest
    container_name: caiman_api
    depends_on:
      - caiman_db
      - caiman_mongo
    volumes:
      - ./volumes/uploads/api:/usr/src/app/uploads
    command: ["node", "index.js"]
    healthcheck:
      interval: 5m
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_NAME: ${API_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      JWT_AUTH_SECRET_KEY: ${JWT_AUTH_SECRET_KEY}
      MONGO_HOST: caiman_mongo
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      MONGO_DATABASE: ${MONGO_DATABASE}

  caiman_frontend:
    restart: always
    build: ./frontend
    image: caiman_frontend:latest
    container_name: caiman_frontend
    healthcheck:
      interval: 5m

  caiman_backend:
    restart: always
    build: ./backend
    image: caiman_backend:latest
    container_name: caiman_backend
    depends_on:
      - caiman_db
    volumes:
      - ./volumes/uploads:/var/www/public/wp-content/uploads
      - ./backend:/var/www/public
    healthcheck:
      interval: 5m
    environment:
      DB_NAME: ${BACKEND_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      WP_DEBUG: ${WP_DEBUG}
      JWT_AUTH_SECRET_KEY: ${JWT_AUTH_SECRET_KEY}
      JWT_AUTH_CORS_ENABLE: ${JWT_AUTH_CORS_ENABLE}
      AGUA_ID_BRAND: ${AGUA_ID_BRAND}
      AGUA_CUSTOMER_CODE: ${AGUA_CUSTOMER_CODE}
      AGUA_HOSTNAME: ${AGUA_HOSTNAME}
      AGUA_ENDPOINT: ${AGUA_ENDPOINT}
      JWT_SOFTWARE_FIELD: ${JWT_SOFTWARE_FIELD}
      JWT_ID_FIELD: ${JWT_ID_FIELD}
      JWT_ISS_FIELD: ${JWT_ISS_FIELD}
      DEFAULT_ROLE: ${DEFAULT_ROLE}
      DEFAULT_USER_ACCESS: ${DEFAULT_USER_ACCESS}
      DEFAULT_LANGUAGE_CODE: ${DEFAULT_LANGUAGE_CODE}
      DEFAULT_ADMIN_CODE: ${DEFAULT_ADMIN_CODE}

  caiman_rabbitmq_auth:
    restart: always
    build: ./rabbimtmq-auth
    image: caiman_rabbitmq_auth:latest
    container_name: caiman_rabbitmq_auth
    command: ["node", "server.js"]
    healthcheck:
      interval: 5m
    environment:
      NODE_ENV: ${NODE_ENV}

  certbot:
    container_name: certbot
    image: gordonchan/auto-letsencrypt
    depends_on:
     - caiman_reverse_proxy
    volumes:
     - ./volumes/letsencrypt/log:/var/log/letsencrypt
     - /var/run/docker.sock:/var/run/docker.sock
     - ./volumes/letsencrypt/data:/etc/letsencrypt
     - ./volumes/letsencrypt/lib:/var/lib/letsencrypt
     - ./volumes/letsencrypt/www:/tmp/letsencrypt/www
     - ./volumes/letsencrypt/certs:/etc/nginx/certs
    environment:
      EMAIL: ${EMAIL}
      SERVER_CONTAINER: ${SERVER_CONTAINER}
      WEBROOT_PATH: ${WEBROOT_PATH}
      CERTS_PATH: ${CERTS_PATH}
      DOMAINS: ${DOMAINS}
      CHECK_FREQ: ${CHECK_FREQ}
    restart: always

  caiman_reverse_proxy:
    restart: always
    build: ./reverse_proxy
    image: caiman_reverse_proxy:latest
    container_name: caiman_reverse_proxy
    volumes:
      - ./volumes/uploads:/data/uploads
      - ./volumes/letsencrypt/certs:/etc/nginx/certs
      - ./volumes/letsencrypt/www:/data/acme
    depends_on:
      - caiman_backend
      - caiman_frontend
      - caiman_broker
    ports:
      - "80:80"
      - "443:443"

  caiman_db:
    image: mariadb
    container_name: caiman_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
      MARIADB_INITDB_SKIP_TZINFO: ${MARIADB_INITDB_SKIP_TZINFO}
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    healthcheck:
      test: "/usr/local/bin/healthcheck.sh --connect"
      interval: 1m  
      timeout: 5s
      retries: 3
      start_period: 1m

  caiman_broker:
    hostname: rabbitmqbroker
    restart: always
    image: caiman_broker:latest
    build: ./rabbitmq
    container_name: caiman_broker
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    depends_on:
      - caiman_rabbitmq_auth
    ports:
      - 15672:15672
    healthcheck:
      interval: 2m

  caiman_phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      depends_on:
        - caiman_db
      environment:
          PMA_HOST: ${PMA_HOST}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}

  caiman_mongo:
    restart: always
    image: caiman_mongo:latest
    build: ../mongo
    container_name: caiman_mongo
    environment:
      MONGO_DATA_DIR: ${MONGO_DATA_DIR}
      MONGO_LOG_DIR: ${MONGO_LOG_DIR}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
    volumes:
      - ./volumes/mongo:/data/db
    command: mongod --logpath=/dev/null # --quiet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  micronova_mongoex:
    image: mongo-express
    container_name: micronova_mongoex
    restart: always
    depends_on:
      - micronova_mongo
    environment:
      ME_CONFIG_SITE_BASEURL: ${ME_CONFIG_SITE_BASEURL}
      ME_CONFIG_OPTIONS_EDITORTHEME: ${ME_CONFIG_OPTIONS_EDITORTHEME}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${ME_CONFIG_MONGODB_AUTH_DATABASE}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      micronova_network:
        ipv4_address: 172.20.0.10
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
